### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by Jawws17** [bitbrute/evillimiter#11] opened 2019-06-05 15:54 UTC
First off i think this might be my fault but whenever i python3 setup.py this shows up.

Download error on https://pypi.org/simple/terminaltables/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'terminaltables' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for terminaltables
error: Could not find suitable distribution for Requirement.parse('terminaltables')

**Comment by leonardus** [comment] 2019-06-05 20:10
Duplicate of #9

**Closed** 2019-06-05 20:23 UTC
Labels: duplicate
