### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kattking16** [bitbrute/evillimiter#37] opened 2019-09-27 19:23 UTC
rootk@LAPTOP-M25MSLPJ:~/evillimiter$ python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages, Command
ModuleNotFoundError: No module named 'setuptools'

**Comment by leonardus** [comment] 2019-10-04 18:26
Duplicate of #12. 
Solution:
> Type `pip3 install setuptools` and the run the setup by typing `python3 setup.py install`
> Finally run the tool: `evillimiter`

**Closed** 2019-10-10 18:25 UTC
